# Generated by Django 5.1.3 on 2024-12-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('book', models.FileField(blank=True, null=True, upload_to='books/products')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('producing_now', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SubType_Protucts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/product_type')),
                ('book', models.FileField(blank=True, null=True, upload_to='books/product_type')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type Protuct',
                'verbose_name_plural': 'Type Protucts',
            },
        ),
        migrations.CreateModel(
            name='Type_Protucts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/product_type')),
                ('book', models.FileField(blank=True, null=True, upload_to='books/product_type')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type Protuct',
                'verbose_name_plural': 'Type Protucts',
            },
        ),
        migrations.CreateModel(
            name='Type_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('info', models.TextField()),
                ('photo', models.ImageField(upload_to='images/errors')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='dab_admin.products')),
            ],
            options={
                'verbose_name': 'Type Error',
                'verbose_name_plural': 'Type Errors',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dab_admin.type_protucts'),
        ),
    ]
