# Generated by Django 5.1.3 on 2024-12-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bot_users',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
