# Generated by Django 5.1.3 on 2024-12-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0002_bot_users_is_active_alter_bot_users_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtype_protucts',
            options={'verbose_name': 'Protuct Sub-Type', 'verbose_name_plural': 'Protuct Sub-Types'},
        ),
        migrations.AddField(
            model_name='products',
            name='product_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dab_admin.subtype_protucts'),
        ),
    ]
