# Generated by Django 5.1.3 on 2025-01-05 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0003_alter_subtype_protucts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_errors',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dab_admin.type_protucts'),
            preserve_default=False,
        ),
    ]
