# Generated by Django 5.1.3 on 2025-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0005_bot_users_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file_id', models.BigIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manual and Info',
                'verbose_name_plural': 'Manuals and Info',
            },
        ),
    ]
