# Generated by Django 5.1.3 on 2025-01-14 16:21

import dab_admin.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0007_alter_manual_info_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=300)),
                ('qr_file', models.FileField(upload_to=dab_admin.models.Qr_code.file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('qr_code_link', models.URLField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=dab_admin.models.Qr_code.qr_code_file_upload_to)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
