# Generated by Django 5.1.3 on 2025-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0008_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
