# Generated by Django 5.1.3 on 2025-01-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0009_qr_code_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='updated_at',
        ),
    ]
