# Generated by Django 5.1.3 on 2025-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_admin', '0010_remove_qr_code_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='book',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='subtype_protucts',
            name='book',
        ),
        migrations.RemoveField(
            model_name='subtype_protucts',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='type_errors',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='type_protucts',
            name='book',
        ),
        migrations.RemoveField(
            model_name='type_protucts',
            name='photo',
        ),
        migrations.AddField(
            model_name='products',
            name='book_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='photo_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type_errors',
            name='photo_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type_protucts',
            name='book_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type_protucts',
            name='photo_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
